### ISSUE TITLE
Is there any accessible download link?

### ISSUE THREAD

**Issue by SongshGeo** [michelegera/alfred-snazzy#2]
Hey! I love your theme, but the download link is broken now. Is there any accessible download link?

**Comment by michelegera** [comment]
Hey @SongshGeo,

seems Alfred removed that link for some reason, so I’ve updated the installation instructions in the README. Let me know how that works for you!

**Comment by SongshGeo** [comment]
Hey, @michelegera , thanks for your update, I successfully import the theme, and I really love it.
